import { DoctorProfile, Specialty } from "@/types/doctor";

export const MOCK_SPECIALTIES: Specialty[] = [
  { id: "s-1", name: "Cardiology Care", slug: "cardiology", icon: "HeartPulse" },
  { id: "s-2", name: "General Medicine", slug: "general-medicine", icon: "Stethoscope" },
  { id: "s-3", name: "Emergency Dentistry", slug: "dentistry", icon: "Smile" },
  { id: "s-4", name: "Pediatric Care", slug: "pediatrics", icon: "Baby" },
  { id: "s-5", name: "Orthopedic & Joint", slug: "orthopedics", icon: "Bone" },
  { id: "s-6", name: "Neurology Solutions", slug: "neurology", icon: "Brain" },
  { id: "s-7", name: "Ophthalmology & Eye", slug: "ophthalmology", icon: "Eye" },
  { id: "s-8", name: "Dermatology Care", slug: "dermatology", icon: "Sparkles" },
];

export const MOCK_DOCTORS: DoctorProfile[] = [
  {
    id: "doc-1",
    userId: "user-1",
    slug: "dr-sarah-jenkins",
    bio: "Dr. Sarah Jenkins is a board-certified Cardiologist with over 12 years of clinical expertise in preventative cardiovascular wellness, ECG interpretation, hypertension management, and remote cardiac triage.",
    experienceYears: 12,
    fee: 800,
    verified: true,
    rating: 4.9,
    totalReviews: 215,
    user: {
      id: "u-1",
      name: "Dr. Sarah Jenkins",
      firstName: "Sarah",
      lastName: "Jenkins",
      email: "sarah.jenkins@telehealth.com",
      image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000001",
    },
    specialties: [
      {
        doctorId: "doc-1",
        specialtyId: "s-1",
        specialty: { id: "s-1", name: "Cardiology Care", slug: "cardiology" },
      },
      {
        doctorId: "doc-1",
        specialtyId: "s-2",
        specialty: { id: "s-2", name: "General Medicine", slug: "general-medicine" },
      },
    ],
    availabilities: [
      { id: "av-1", doctorId: "doc-1", dayOfWeek: 1, startTime: "09:00 AM", endTime: "12:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-2", doctorId: "doc-1", dayOfWeek: 1, startTime: "02:30 PM", endTime: "06:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-3", doctorId: "doc-1", dayOfWeek: 3, startTime: "10:00 AM", endTime: "01:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-4", doctorId: "doc-1", dayOfWeek: 4, startTime: "04:00 PM", endTime: "08:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-5", doctorId: "doc-1", dayOfWeek: 6, startTime: "11:00 AM", endTime: "03:00 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-1",
        rating: 5,
        comment: "Dr. Sarah was extremely attentive and explained my ECG results thoroughly. Best telemedicine experience I've had!",
        createdAt: "2026-09-12T10:00:00Z",
        patient: { id: "p-1", user: { name: "Maddison Reichel" } },
      },
      {
        id: "r-2",
        rating: 5,
        comment: "Very professional consultation. Prescriptions were sent to my patient dashboard within minutes.",
        createdAt: "2026-09-08T14:30:00Z",
        patient: { id: "p-2", user: { name: "David Kim" } },
      },
    ],
  },
  {
    id: "doc-2",
    userId: "user-2",
    slug: "dr-fletcher-waelchi",
    bio: "Dr. Fletcher Waelchi is a seasoned General Physician specializing in acute fever triage, lifestyle medicine, routine health checkups, and chronic disease counseling with over 10 years of practice.",
    experienceYears: 10,
    fee: 500,
    verified: true,
    rating: 4.9,
    totalReviews: 184,
    user: {
      id: "u-2",
      name: "Dr. Fletcher Waelchi",
      firstName: "Fletcher",
      lastName: "Waelchi",
      email: "fletcher@telehealth.com",
      image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000002",
    },
    specialties: [
      {
        doctorId: "doc-2",
        specialtyId: "s-2",
        specialty: { id: "s-2", name: "General Medicine", slug: "general-medicine" },
      },
    ],
    availabilities: [
      { id: "av-6", doctorId: "doc-2", dayOfWeek: 0, startTime: "10:00 AM", endTime: "01:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-7", doctorId: "doc-2", dayOfWeek: 2, startTime: "03:00 PM", endTime: "07:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-8", doctorId: "doc-2", dayOfWeek: 4, startTime: "09:30 AM", endTime: "01:30 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-3",
        rating: 5,
        comment: "Listened to my symptoms carefully and provided clear dietary and medication guidelines.",
        createdAt: "2026-09-10T11:20:00Z",
        patient: { id: "p-3", user: { name: "Benjamin West" } },
      },
    ],
  },
  {
    id: "doc-3",
    userId: "user-3",
    slug: "dr-fredrick-auer",
    bio: "Dr. Fredrick Auer is an Orthopedic and Joint Specialist with 14 years of surgical and telehealth rehab experience diagnosing sports injuries, posture strain, arthritis, and musculoskeletal pain.",
    experienceYears: 14,
    fee: 900,
    verified: true,
    rating: 4.8,
    totalReviews: 128,
    user: {
      id: "u-3",
      name: "Dr. Fredrick Auer",
      firstName: "Fredrick",
      lastName: "Auer",
      email: "fredrick@telehealth.com",
      image: "https://images.unsplash.com/photo-1594824813590-7892f3922f3f?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000003",
    },
    specialties: [
      {
        doctorId: "doc-3",
        specialtyId: "s-5",
        specialty: { id: "s-5", name: "Orthopedic & Joint", slug: "orthopedics" },
      },
    ],
    availabilities: [
      { id: "av-9", doctorId: "doc-3", dayOfWeek: 1, startTime: "10:00 AM", endTime: "02:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-10", doctorId: "doc-3", dayOfWeek: 3, startTime: "04:00 PM", endTime: "08:00 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-4",
        rating: 5,
        comment: "Very helpful physiotherapy and ergonomics advice for my chronic lower back strain.",
        createdAt: "2026-09-05T09:15:00Z",
        patient: { id: "p-4", user: { name: "Sophia Reynolds" } },
      },
    ],
  },
  {
    id: "doc-4",
    userId: "user-4",
    slug: "dr-michael-chen",
    bio: "Dr. Michael Chen is a Consultant Neurologist with extensive research in migraine management, peripheral neuropathies, stress disorders, and brain wellness via secure virtual consultations.",
    experienceYears: 15,
    fee: 1000,
    verified: true,
    rating: 5.0,
    totalReviews: 190,
    user: {
      id: "u-4",
      name: "Dr. Michael Chen",
      firstName: "Michael",
      lastName: "Chen",
      email: "michael@telehealth.com",
      image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000004",
    },
    specialties: [
      {
        doctorId: "doc-4",
        specialtyId: "s-6",
        specialty: { id: "s-6", name: "Neurology Solutions", slug: "neurology" },
      },
    ],
    availabilities: [
      { id: "av-11", doctorId: "doc-4", dayOfWeek: 2, startTime: "11:00 AM", endTime: "03:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-12", doctorId: "doc-4", dayOfWeek: 5, startTime: "02:00 PM", endTime: "06:00 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-5",
        rating: 5,
        comment: "Excellent neurologist. Took the time to understand my migraine triggers and altered my medications effectively.",
        createdAt: "2026-09-02T16:40:00Z",
        patient: { id: "p-5", user: { name: "Alexander Wright" } },
      },
    ],
  },
  {
    id: "doc-5",
    userId: "user-5",
    slug: "dr-amanda-miller",
    bio: "Dr. Amanda Miller is a compassionate Pediatrician with 8 years of experience helping parents with infant nutrition, child developmental milestones, viral fever, and pediatric wellness care.",
    experienceYears: 8,
    fee: 600,
    verified: true,
    rating: 4.9,
    totalReviews: 172,
    user: {
      id: "u-5",
      name: "Dr. Amanda Miller",
      firstName: "Amanda",
      lastName: "Miller",
      email: "amanda@telehealth.com",
      image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000005",
    },
    specialties: [
      {
        doctorId: "doc-5",
        specialtyId: "s-4",
        specialty: { id: "s-4", name: "Pediatric Care", slug: "pediatrics" },
      },
    ],
    availabilities: [
      { id: "av-13", doctorId: "doc-5", dayOfWeek: 0, startTime: "09:00 AM", endTime: "01:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-14", doctorId: "doc-5", dayOfWeek: 3, startTime: "03:00 PM", endTime: "07:00 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-6",
        rating: 5,
        comment: "Dr. Amanda was so warm and kind with my 4-year-old daughter during the video call.",
        createdAt: "2026-08-28T14:10:00Z",
        patient: { id: "p-6", user: { name: "Emily Watson" } },
      },
    ],
  },
  {
    id: "doc-6",
    userId: "user-6",
    slug: "dr-lucas-vance",
    bio: "Dr. Lucas Vance is an Emergency Dental Surgeon and oral health expert specializing in virtual dental triage, acute toothache relief, gum care, and post-surgery telehealth guidance.",
    experienceYears: 9,
    fee: 550,
    verified: true,
    rating: 4.8,
    totalReviews: 95,
    user: {
      id: "u-6",
      name: "Dr. Lucas Vance",
      firstName: "Lucas",
      lastName: "Vance",
      email: "lucas@telehealth.com",
      image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=800&q=80",
      phone: "+880 1711-000006",
    },
    specialties: [
      {
        doctorId: "doc-6",
        specialtyId: "s-3",
        specialty: { id: "s-3", name: "Emergency Dentistry", slug: "dentistry" },
      },
    ],
    availabilities: [
      { id: "av-15", doctorId: "doc-6", dayOfWeek: 1, startTime: "11:00 AM", endTime: "04:00 PM", consultationDuration: 30, isActive: true },
      { id: "av-16", doctorId: "doc-6", dayOfWeek: 5, startTime: "09:00 AM", endTime: "02:00 PM", consultationDuration: 30, isActive: true },
    ],
    reviews: [
      {
        id: "r-7",
        rating: 5,
        comment: "Instant consultation when I had severe wisdom tooth pain on a weekend. Highly recommended!",
        createdAt: "2026-08-22T18:00:00Z",
        patient: { id: "p-7", user: { name: "Liam Johnson" } },
      },
    ],
  },
];
